### PR TITLE
Post SessionID to Parent

### PR DESCRIPTION
**Pull request by yen-tt**
send the sessionId in the same message that the queryId is being sent

J=SLAP-1450
TEST=manual

Launched iframe test site, performed a search and verified through console log in iframe-common.js onMessage() that a message is delivered to parent page with queryId and sessionId.

### CODE REVIEW

**Review by oshi97 — APPROVED** [review]

**Comment by oshi97** [comment]
I know the item says this should go in develop, but I thought this would only be needed in the case deflection branch?

**Comment by yen-tt** [comment]
> I know the item says this should go in develop, but I thought this would only be needed in the case deflection branch?

@cea2aj commits in case deflection feature branch is also in develop so I assume both need to be updated?

**Comment by cea2aj** [comment]
> > I know the item says this should go in develop, but I thought this would only be needed in the case deflection branch?
> 
> @cea2aj commits in case deflection feature branch is also in develop so I assume both need to be updated?

yes, we are putting case deflection work in a feature branch and in develop

**Review by cea2aj — APPROVED** [review]

**Comment by oshi97** [comment]
> > > I know the item says this should go in develop, but I thought this would only be needed in the case deflection branch?
> > 
> > 
> > @cea2aj commits in case deflection feature branch is also in develop so I assume both need to be updated?
> 
> yes, we are putting case deflection work in a feature branch and in develop

okay cool! for some reason I was imagining we would cherry-pick this into the feature branch, but it probably makes more sense to just to rebase the feature branch onto develop

**Comment by oshi97** [comment]
> > > > I know the item says this should go in develop, but I thought this would only be needed in the case deflection branch?
> > > 
> > > 
> > > @cea2aj commits in case deflection feature branch is also in develop so I assume both need to be updated?
> > 
> > 
> > yes, we are putting case deflection work in a feature branch and in develop
> 
> okay cool! for some reason I was imagining we would cherry-pick this into the feature branch, but it probably makes more sense to just to rebase the feature branch onto develop

more response pyramids

**Pull request merged**
